-- Mapas de asientos (seats.io) y enlace en evento.
-- Ejecutar en Supabase SQL Editor si no usas migraciones CLI.

CREATE TABLE IF NOT EXISTS mapa_asiento (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  seatsio_chart_key text NOT NULL UNIQUE,
  id_administrador bigint NULL REFERENCES administradores (id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE evento
  ADD COLUMN IF NOT EXISTS id_mapa_asiento bigint NULL REFERENCES mapa_asiento (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_evento_mapa_asiento ON evento (id_mapa_asiento);
CREATE INDEX IF NOT EXISTS idx_mapa_asiento_admin ON mapa_asiento (id_administrador);

ALTER TABLE mapa_asiento ENABLE ROW LEVEL SECURITY;

-- Ajusta políticas según tu modelo de auth; esto permite que el anon key del demo funcione como el resto de tablas.
CREATE POLICY "mapa_asiento_select" ON mapa_asiento FOR SELECT USING (true);
CREATE POLICY "mapa_asiento_insert" ON mapa_asiento FOR INSERT WITH CHECK (true);
CREATE POLICY "mapa_asiento_update" ON mapa_asiento FOR UPDATE USING (true);
CREATE POLICY "mapa_asiento_delete" ON mapa_asiento FOR DELETE USING (true);
